# Generated by Django 4.2.1 on 2023-05-11 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('emission_factor', models.FloatField(blank=True, null=True)),
                ('total_emission', models.FloatField(blank=True, help_text='Unit in kg', null=True)),
                ('lifetime', models.PositiveIntegerField(blank=True, null=True)),
                ('acquisition_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coreapp.report')),
            ],
        ),
    ]
