# Generated by Django 4.2.1 on 2023-05-13 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0002_alter_source_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReductionStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reductionStrategies', to='coreapp.report')),
            ],
        ),
        migrations.CreateModel(
            name='ReductionModification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('value_ratio', models.FloatField(blank=True, null=True)),
                ('emission_factor_change', models.FloatField(blank=True, null=True)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coreapp.source')),
                ('strategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='coreapp.reductionstrategy')),
            ],
        ),
        migrations.AddField(
            model_name='source',
            name='strategy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='coreapp.reductionstrategy'),
        ),
    ]
