# Generated by Django 4.2.1 on 2023-05-13 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0003_reductionstrategy_reductionmodification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='strategy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sourcesStrategy', to='coreapp.reductionstrategy'),
        ),
    ]
