# Generated by Django 4.2.1 on 2023-05-24 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0005_alter_reductionmodification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reductionmodification',
            name='modification_start_year',
            field=models.PositiveSmallIntegerField(default=2020),
            preserve_default=False,
        ),
    ]
