# Generated by Django 4.2.1 on 2023-05-24 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0006_reductionmodification_modification_start_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reductionmodification',
            old_name='value_ratio',
            new_name='value_modification',
        ),
    ]
